"""Request-scoped dependency accessors."""

from __future__ import annotations

from fastapi import Request

from api.firemark.control_plane.service import CertificateService


def get_certificate_service(request: Request) -> CertificateService:
    """Return the application-injected service without constructing clients."""
    return request.app.state.certificate_service  # type: ignore[no-any-return]


def get_request_id(request: Request) -> str:
    """Return the correlation identifier generated by FIREMARK middleware."""
    return str(request.state.request_id)
