"""Request-scoped dependency accessors."""

from __future__ import annotations

from fastapi import Request

from api.firemark.api.errors import APIError
from api.firemark.control_plane.service import CertificateService
from api.firemark.generate_and_seal import GenerateAndSealService


def get_certificate_service(request: Request) -> CertificateService:
    """Return the application-injected service without constructing clients."""
    return request.app.state.certificate_service  # type: ignore[no-any-return]


def get_request_id(request: Request) -> str:
    """Return the correlation identifier generated by FIREMARK middleware."""
    return str(request.state.request_id)


def get_generate_and_seal_service(request: Request) -> GenerateAndSealService:
    service = request.app.state.generate_and_seal_service
    if service is None:
        raise APIError(
            503,
            "GENERATION_NOT_CONFIGURED",
            "Generate & Seal production dependencies are not configured.",
        )
    return service  # type: ignore[no-any-return]
