"""Explicit opt-in, isolated Google Gemini image-provider checkpoint.

The checkpoint submits at most one Interactions generation request. A read-only
model preflight is deliberately NOT part of this path; use
``scripts/diagnose_gemini_access.py`` for read-only model diagnostics so a
model-listing endpoint can never block a valid generation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

from dotenv import load_dotenv
from pydantic import BaseModel, ConfigDict, Field, field_validator

from api.firemark.generation.gemini_provider import (
    GEMINI_INTERACTIONS_PATH,
    GEMINI_OUTPUT_MIME_TYPE,
    GeminiImageProvider,
)
from api.firemark.generation.models import GeneratedImage, GenerationRequest
from api.firemark.generation.provider import GenerationProviderError
from api.firemark.generation.provider_identity import (
    GOOGLE_GEMINI_PROVIDER,
    provider_model_display_name,
)
from api.firemark.settings import GeminiImageConfig, Settings

INFORMATIONAL_EXIT_CODE = 2
DEFAULT_ENV_FILE = Path(__file__).resolve().parents[1] / ".env"
DEFAULT_CHECKPOINT = Path(".artifacts/gemini-image-provider-checkpoint.json")
DEFAULT_PRIVATE_ROOT = Path(".artifacts/gemini-image-provider-private")
SMOKE_REQUEST_ID = "firemark-gemini-provider-smoke"
SMOKE_PROMPT = (
    "A premium forensic fire-shaped authenticity seal on a dark neutral background, "
    "clean geometric design, no text."
)
STAGES = (
    "configuration_validation",
    "request_construction",
    "checkpoint_before_submission",
    "provider_generation",
    "response_validation",
    "png_validation",
    "source_hash",
    "checkpoint_after_generation",
)

SafeCategory = Literal[
    "OK",
    "CONFIGURATION_ERROR",
    "AUTHENTICATION_FAILURE",
    "PERMISSION_DENIED",
    "QUOTA_OR_BILLING_FAILURE",
    "RATE_LIMIT",
    "INVALID_REQUEST",
    "MODEL_UNSUPPORTED",
    "SAFETY_REJECTION",
    "TIMEOUT",
    "PROVIDER_UNAVAILABLE",
    "MALFORMED_RESPONSE",
    "NON_PNG_RESPONSE",
    "RESPONSE_TOO_LARGE",
    "AMBIGUOUS_PRIOR_SUBMISSION",
    "SAFE_UNEXPECTED_FAILURE",
]

PROVIDER_CATEGORIES: dict[str, SafeCategory] = {
    "authentication": "AUTHENTICATION_FAILURE",
    "permission_denied": "PERMISSION_DENIED",
    "quota_or_billing": "QUOTA_OR_BILLING_FAILURE",
    "rate_limit": "RATE_LIMIT",
    "invalid_request": "INVALID_REQUEST",
    "model_or_size_unsupported": "MODEL_UNSUPPORTED",
    "safety_rejection": "SAFETY_REJECTION",
    "timeout": "TIMEOUT",
    "unavailable": "PROVIDER_UNAVAILABLE",
    "malformed_response": "MALFORMED_RESPONSE",
    "non_png_response": "NON_PNG_RESPONSE",
    "response_too_large": "RESPONSE_TOO_LARGE",
}

#: Only a definitive provider rejection received before any generated bytes may
#: be retried, and only when the operator explicitly authorizes it.
DEFINITIVE_RETRY_CODES = frozenset(
    {
        "authentication",
        "permission_denied",
        "quota_or_billing",
        "invalid_request",
        "model_or_size_unsupported",
    }
)

OperationState = Literal[
    "request_ready",
    "provider_call_started",
    "provider_rejected",
    "generated",
    "complete",
]


class SafeSmokeError(RuntimeError):
    """Category-only local failure."""

    def __init__(self, category: SafeCategory) -> None:
        self.category = category
        super().__init__(category)


class GeminiProviderCheckpoint(BaseModel):
    """Closed safe checkpoint; generated bytes live in a separate ignored file."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    schema_version: Literal["firemark.gemini-image-provider-checkpoint.v1"] = (
        "firemark.gemini-image-provider-checkpoint.v1"
    )
    operation_state: OperationState
    provider: Literal["google_gemini"] = GOOGLE_GEMINI_PROVIDER
    model: str
    media_type: Literal["image"] = "image"
    mime_type: Literal["image/png"] = "image/png"
    request_id: str
    created_at: datetime
    new_provider_calls: int = Field(default=0, ge=0, le=1)
    prior_rejected_calls: int = Field(default=0, ge=0)
    provider_failure_code: str | None = None
    provider_failure_status: int | None = None
    provider_safe_reason_code: str | None = None
    provider_retry_allowed: bool = False
    source_sha256: str | None = None
    generated_byte_count: int | None = Field(default=None, gt=0)
    source_path: str | None = None
    current_stage: str | None = None
    stage_results: tuple[dict[str, str], ...] = ()

    @field_validator("created_at")
    @classmethod
    def normalize_timestamp(cls, value: datetime) -> datetime:
        if value.tzinfo is None or value.utcoffset() is None:
            raise ValueError("Checkpoint timestamps must be timezone-aware")
        return value.astimezone(UTC)

    @field_validator("source_sha256")
    @classmethod
    def validate_optional_digest(cls, value: str | None) -> str | None:
        if value is not None and (
            len(value) != 64 or any(character not in "0123456789abcdef" for character in value)
        ):
            raise ValueError("Checkpoint digest is invalid")
        return value


def _atomic_write(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    os.close(descriptor)
    temporary = Path(temporary_name)
    try:
        temporary.write_bytes(payload)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


class CheckpointStore:
    """Atomic allowlisted checkpoint and private-byte persistence."""

    def __init__(self, path: Path, private_root: Path) -> None:
        self.path = path
        self.private_root = private_root

    def exists(self) -> bool:
        return self.path.is_file()

    def read(self) -> GeminiProviderCheckpoint:
        try:
            return GeminiProviderCheckpoint.model_validate_json(self.path.read_bytes())
        except Exception:
            raise SafeSmokeError("SAFE_UNEXPECTED_FAILURE") from None

    def write(self, checkpoint: GeminiProviderCheckpoint) -> GeminiProviderCheckpoint:
        _atomic_write(
            self.path,
            json.dumps(
                checkpoint.model_dump(mode="json"), ensure_ascii=True, indent=2, sort_keys=True
            ).encode("utf-8"),
        )
        return checkpoint

    def update(self, **values: object) -> GeminiProviderCheckpoint:
        updated = GeminiProviderCheckpoint.model_validate(
            self.read().model_copy(update=values).model_dump()
        )
        return self.write(updated)

    def mark_stage(self, stage: str, completed: Sequence[dict[str, str]]) -> None:
        if self.exists():
            self.update(current_stage=stage, stage_results=tuple(completed))

    def persist_generated(self, image: GeneratedImage) -> GeminiProviderCheckpoint:
        """Store valid PNG bytes before anything else can fail."""
        checkpoint = self.read()
        if (
            checkpoint.new_provider_calls != 1
            or checkpoint.operation_state != "provider_call_started"
        ):
            raise SafeSmokeError("SAFE_UNEXPECTED_FAILURE")
        destination = self.private_root / checkpoint.request_id / "source.png"
        _atomic_write(destination, image.data)
        return self.update(
            operation_state="generated",
            source_sha256=hashlib.sha256(image.data).hexdigest(),
            generated_byte_count=len(image.data),
            source_path=str(destination.resolve()),
            provider_failure_code=None,
            provider_failure_status=None,
            provider_safe_reason_code=None,
            provider_retry_allowed=False,
        )

    def persist_provider_failure(self, exc: GenerationProviderError) -> None:
        checkpoint = self.read()
        if checkpoint.operation_state != "provider_call_started":
            raise SafeSmokeError("SAFE_UNEXPECTED_FAILURE")
        self.update(
            operation_state="provider_rejected",
            prior_rejected_calls=checkpoint.prior_rejected_calls + 1,
            provider_failure_code=exc.code,
            provider_failure_status=exc.status_code,
            provider_safe_reason_code=exc.safe_reason_code,
            provider_retry_allowed=exc.code in DEFINITIVE_RETRY_CODES,
        )

    def recover_image(self, model: str) -> GeneratedImage:
        """Rebuild the generated image from persisted bytes without calling Gemini."""
        checkpoint = self.read()
        if checkpoint.source_path is None or checkpoint.source_sha256 is None:
            raise SafeSmokeError("SAFE_UNEXPECTED_FAILURE")
        try:
            data = Path(checkpoint.source_path).read_bytes()
        except OSError:
            raise SafeSmokeError("SAFE_UNEXPECTED_FAILURE") from None
        if hashlib.sha256(data).hexdigest() != checkpoint.source_sha256:
            raise SafeSmokeError("SAFE_UNEXPECTED_FAILURE")
        return GeneratedImage(
            data=data,
            provider=GOOGLE_GEMINI_PROVIDER,
            model=model,
            provider_created_at=checkpoint.created_at,
            ai_generated=True,
        )


@dataclass(frozen=True)
class SmokeOutcome:
    category: SafeCategory
    stages: tuple[tuple[str, str], ...]
    config: GeminiImageConfig | None = None
    image: GeneratedImage | None = None
    source_sha256: str | None = None
    provider_code: str | None = None
    provider_status: int | None = None
    safe_reason_code: str | None = None
    provider_calls: int = 0
    recovered: bool = False
    retry_permitted: bool = False


class StageTracker:
    def __init__(self, store: CheckpointStore) -> None:
        self.store = store
        self.current = STAGES[0]
        self.rows: list[tuple[str, str]] = []

    def begin(self, stage: str) -> None:
        if stage != self.current:
            self.rows.append((self.current, "PASS"))
            self.current = stage
            self.store.mark_stage(stage, [{"stage": name, "status": result} for name, result in self.rows])

    def success(self) -> tuple[tuple[str, str], ...]:
        self.rows.append((self.current, "PASS"))
        return tuple(self.rows)

    def failure(self) -> tuple[tuple[str, str], ...]:
        self.rows.append((self.current, "FAIL"))
        return tuple(self.rows)


def _load_gemini_config() -> GeminiImageConfig:
    names = {
        "GEMINI_API_KEY": "gemini_api_key",
        "GEMINI_IMAGE_MODEL": "gemini_image_model",
        "FIREMARK_GENERATION_TIMEOUT_SECONDS": "generation_timeout_seconds",
        "FIREMARK_MAX_GENERATED_IMAGE_BYTES": "max_generated_image_bytes",
    }
    values = {
        field: value
        for name, field in names.items()
        if (value := os.getenv(name)) not in (None, "")
    }
    return Settings.model_validate(values).require_gemini_image_config()


def _category(
    exc: Exception, stage: str
) -> tuple[SafeCategory, str | None, int | None, str | None]:
    if isinstance(exc, SafeSmokeError):
        return exc.category, None, None, None
    if isinstance(exc, GenerationProviderError):
        return (
            PROVIDER_CATEGORIES.get(exc.code, "SAFE_UNEXPECTED_FAILURE"),
            exc.code,
            exc.status_code,
            exc.safe_reason_code,
        )
    if stage == "configuration_validation":
        return "CONFIGURATION_ERROR", None, None, None
    return "SAFE_UNEXPECTED_FAILURE", None, None, None


def expected_request_payload(model: str, prompt: str) -> dict[str, Any]:
    """The documented minimal Interactions request FIREMARK must submit."""
    return {
        "model": model,
        "input": [{"type": "text", "text": prompt}],
        "response_format": {"type": "image", "mime_type": GEMINI_OUTPUT_MIME_TYPE},
    }


def _resume_state(
    store: CheckpointStore,
    config: GeminiImageConfig,
    *,
    allow_definitive_retry: bool,
) -> GeminiProviderCheckpoint:
    """Load or create the checkpoint and refuse an ambiguous second submission."""
    if not store.exists():
        return store.write(
            GeminiProviderCheckpoint(
                operation_state="request_ready",
                model=config.model,
                request_id=SMOKE_REQUEST_ID,
                created_at=datetime.now(UTC),
            )
        )
    checkpoint = store.read()
    if checkpoint.model != config.model:
        raise SafeSmokeError("CONFIGURATION_ERROR")
    if checkpoint.operation_state == "provider_call_started":
        # A previous submission's outcome was never durably captured. Failing
        # closed is mandatory: a second call could be a duplicate billable
        # generation for an image that may already exist.
        raise SafeSmokeError("AMBIGUOUS_PRIOR_SUBMISSION")
    if checkpoint.operation_state == "provider_rejected":
        if not (allow_definitive_retry and _retry_allowed(checkpoint)):
            raise SafeSmokeError("AMBIGUOUS_PRIOR_SUBMISSION")
        return store.update(
            operation_state="request_ready",
            new_provider_calls=0,
            provider_failure_code=None,
            provider_failure_status=None,
            provider_safe_reason_code=None,
            provider_retry_allowed=False,
            current_stage=None,
        )
    return checkpoint


def _retry_allowed(checkpoint: GeminiProviderCheckpoint) -> bool:
    """Permit retry only after one definitive rejection with no captured bytes."""
    return bool(
        checkpoint.operation_state == "provider_rejected"
        and checkpoint.provider_retry_allowed
        and checkpoint.provider_failure_code in DEFINITIVE_RETRY_CODES
        and checkpoint.prior_rejected_calls == 1
        and checkpoint.source_sha256 is None
        and checkpoint.source_path is None
    )


def execute_live(
    *,
    config_loader: Callable[[], GeminiImageConfig] = _load_gemini_config,
    provider_factory: Callable[..., GeminiImageProvider] = GeminiImageProvider,
    checkpoint_path: Path = DEFAULT_CHECKPOINT,
    private_root: Path = DEFAULT_PRIVATE_ROOT,
    allow_definitive_retry: bool = False,
) -> SmokeOutcome:
    """Submit at most one Gemini generation request and persist safe state."""
    store = CheckpointStore(checkpoint_path, private_root)
    tracker = StageTracker(store)
    config: GeminiImageConfig | None = None
    image: GeneratedImage | None = None
    digest: str | None = None
    calls = 0
    recovered = False
    try:
        config = config_loader()
        provider = provider_factory(
            api_key=config.api_key.get_secret_value(),
            timeout_seconds=config.timeout_seconds,
            max_image_bytes=config.max_image_bytes,
        )
        tracker.begin("request_construction")
        request = GenerationRequest(
            prompt=SMOKE_PROMPT,
            model=config.model,
            size="auto",
            request_id=SMOKE_REQUEST_ID,
        )
        payload = GeminiImageProvider.build_request_parameters(request)
        if payload != expected_request_payload(config.model, SMOKE_PROMPT):
            raise SafeSmokeError("INVALID_REQUEST")
        tracker.begin("checkpoint_before_submission")
        checkpoint = _resume_state(
            store, config, allow_definitive_retry=allow_definitive_retry
        )
        tracker.begin("provider_generation")
        if checkpoint.operation_state in {"generated", "complete"}:
            recovered = True
            image = store.recover_image(config.model)
        else:
            store.update(operation_state="provider_call_started", new_provider_calls=1)
            calls = 1
            try:
                image = provider.generate_image(request)
            except GenerationProviderError as exc:
                store.persist_provider_failure(exc)
                raise
            checkpoint = store.persist_generated(image)
        tracker.begin("response_validation")
        if image.provider != GOOGLE_GEMINI_PROVIDER or not image.ai_generated:
            raise SafeSmokeError("MALFORMED_RESPONSE")
        tracker.begin("png_validation")
        if (
            image.media_type != GEMINI_OUTPUT_MIME_TYPE
            or image.file_extension != "png"
            or not image.data.startswith(b"\x89PNG\r\n\x1a\n")
        ):
            raise SafeSmokeError("NON_PNG_RESPONSE")
        if len(image.data) > config.max_image_bytes:
            raise SafeSmokeError("RESPONSE_TOO_LARGE")
        tracker.begin("source_hash")
        digest = hashlib.sha256(image.data).hexdigest()
        tracker.begin("checkpoint_after_generation")
        final = store.update(operation_state="complete", current_stage=None)
        if final.source_sha256 != digest:
            raise SafeSmokeError("SAFE_UNEXPECTED_FAILURE")
        return SmokeOutcome(
            category="OK",
            stages=tracker.success(),
            config=config,
            image=image,
            source_sha256=digest,
            provider_calls=calls,
            recovered=recovered,
        )
    except Exception as exc:
        category, code, status, reason = _category(exc, tracker.current)
        retry_permitted = store.exists() and _retry_allowed(store.read())
        return SmokeOutcome(
            category=category,
            stages=tracker.failure(),
            config=config,
            image=image,
            source_sha256=digest,
            provider_code=code,
            provider_status=status,
            safe_reason_code=reason,
            provider_calls=calls,
            recovered=recovered,
            retry_permitted=retry_permitted,
        )


def _print_outcome(outcome: SmokeOutcome) -> None:
    if outcome.config is not None:
        print(f"provider: {GOOGLE_GEMINI_PROVIDER}")
        print(f"configured model: {outcome.config.model}")
        display_name = provider_model_display_name(GOOGLE_GEMINI_PROVIDER, outcome.config.model)
        print(f"provider model name: {display_name or 'UNDECLARED'}")
    print(f"generation endpoint: {GEMINI_INTERACTIONS_PATH}")
    print("read-only model preflight: NOT PERFORMED (diagnostic-only)")
    print(f"new generation requests: {outcome.provider_calls}")
    print(f"recovered from persisted bytes: {str(outcome.recovered).lower()}")
    if outcome.image is not None:
        print(f"generated byte count: {len(outcome.image.data)}")
        print(f"SHA-256: {outcome.source_sha256 or 'UNAVAILABLE'}")
        print(f"ai_generated: {str(outcome.image.ai_generated).lower()}")
    print("stage table:")
    for stage, status in outcome.stages:
        print(f"{status}: {stage}")
    print(f"normalized safe category: {outcome.category}")
    if outcome.provider_status is not None:
        print(f"provider HTTP status: {outcome.provider_status}")
    if outcome.safe_reason_code is not None:
        print(f"provider safe reason: {outcome.safe_reason_code}")
    if outcome.category != "OK":
        print(f"manually authorized retry permitted: {str(outcome.retry_permitted).lower()}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run one isolated Google Gemini image-provider verification checkpoint."
    )
    parser.add_argument(
        "--live",
        action="store_true",
        help="Allow at most one real Google Gemini Interactions generation request.",
    )
    parser.add_argument(
        "--allow-definitive-retry",
        action="store_true",
        help=(
            "Authorize one retry after a definitive provider rejection that produced "
            "no generated bytes. Ambiguous outcomes are never retried."
        ),
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if not args.live:
        print("INFO: --live not supplied; zero network calls were made.")
        print("INFO: no Gemini client was constructed and no provider cost was incurred.")
        return INFORMATIONAL_EXIT_CODE
    load_dotenv(DEFAULT_ENV_FILE, override=False)
    outcome = execute_live(allow_definitive_retry=args.allow_definitive_retry)
    _print_outcome(outcome)
    return 0 if outcome.category == "OK" else 1


if __name__ == "__main__":
    raise SystemExit(main())
